---

- name: Logrotate | package
  tags:
  - package
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - logrotate

- name: Logrotate | config
  tags:
  - config
  template:
    src: "{{ item }}.j2"
    dest: "/etc/{{ item }}"
  with_items:
    - logrotate.conf

- name: Logrotate | log archive dir
  tags:
  - dir
  file:
    path: /var/log/old
    state: directory
    owner: root
    group: adm
    mode: 0770
