---

- name: Logrotate | package
  tags:
  - package
  package:
    name: logrotate

- name: Logrotate | config
  tags:
    - config
  copy:
    src: logrotate.conf
    dest: /etc/

- name: Logrotate | clear pkg config
  tags:
    - config
  file:
    path: "/etc/logrotate.d/{{ item }}"
    state: absent
  loop: "{{ q('list', logrotate_clear) }}"
