---

- name: Logrotate | package
  tags:
  - package
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - logrotate

- name: Logrotate | config
  tags:
    - config
  copy:
    src: logrotate.conf
    dest: /etc/

- name: Logrotate | clear pkg config
  tags:
    - config
  file:
    path: "/etc/logrotate.d/{{ item }}"
    state: absent
  with_items: "{{ logrotate_clear }}"
