#! /usr/bin/env ansible-playbook
# Configure logrotate role
# Replace 'all' with your own inventory group
---
- name: logrotate | roll log files
  hosts: all
  roles:
  - role: logrotate
    tags:
    - log
    - syslog
    - logrotate
